root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./bin/app ./cmd/"
bin = "./bin/app"
delay = 2000
include_ext = ["go"]
include_file = ["main.go"]
include_dir = ["cmd", "internal"]
exclude_regex = ["_test.go$", "_gen.go$"]
stop_on_error = true

[log]
main_only = true